title:        APIStrat Austin 2015
url:          http://austin2015.apistrat.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

production_url : http://austin2015.apistrat.com

BASE_PATH : http://austin2015.apistrat.com

categories_path : /categories.html
tags_path : /tags.html

featured_speakers:
  - name: "Neha Sampat"
    company: Built.io
    company_url: http://built.io
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/neha-sampat-headshot.jpeg
    description: CEO of @Builtio | Co-founder of @raweng & @kurbkarma | Advocate for Women in Leadership
    slug: /speakers/neha-sampat/
    twitter: https://twitter.com/nehasf
  - name: Dion Hinchcliffe
    company: 7Summits
    company_url: http://www.7summitsinc.com/
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/dion_hinchcliffe-headshot.jpg
    description: Chief Strategy Officer, business strategist, enterprise architect, keynote speaker, author, & futurist.
    slug: /speakers/dion-hinchcliffe/
    twitter: https://twitter.com/dhinchcliffe
