title:        APIStrat Austin 2015
url:          http://austin2015.apistrat.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

production_url : http://austin2015.apistrat.com

BASE_PATH : http://austin2015.apistrat.com

categories_path : /categories.html
tags_path : /tags.html

featured_speakers:
  - name: "Neha Sampat"
    company: Built.io
    company_url: http://built.io
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/neha-sampat-headshot.jpeg
    description: CEO of @Builtio | Co-founder of @raweng & @kurbkarma | Advocate for Women in Leadership
    slug: /speakers/neha-sampat/
    twitter: https://twitter.com/nehasf
  - name: Dion Hinchcliffe
    company: 7Summits
    company_url: http://www.7summitsinc.com/
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/dion_hinchcliffe-headshot.jpg
    description: Chief Strategy Officer, business strategist, enterprise architect, keynote speaker, author, & futurist.
    slug: /speakers/dion-hinchcliffe/
    twitter: https://twitter.com/dhinchcliffe
  - name: Lori MacVittie
    company: F5 Networks
    company_url: https://f5.com/
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/lorie-macvittie.jpg
    description: Lori MacVittie is a subject matter expert on emerging technology responsible for education and evangelism across F5s entire product suite.
    slug: /speakers/lori-macvittie/
    twitter: https://twitter.com/lmacvittie
  - name: Ashley Hathaway
    company: IBM Watson Group
    company_url: http://www.ibm.com/smarterplanet/us/en/ibmwatson/
    image: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/speakers/ashley-hathway.jpeg
    description: As part of a strong team she helps to prioritize, drive requirements, and realize the vision of a successful product for the IBM Watson Developer Cloud in Austin, Texas.
    slug: /speakers/ashley-hathaway/
    twitter: https://twitter.com/ash_hathaway

sponsors:
  - name: 3Scale
    link: http://www.3scale.net/
    logo: http://apidaysberlin2015.apistrat.com/wp-content/uploads/2014/11/3scale-logo-new.png
  - name: Walgreens
    link: https://developer.walgreens.com/
    logo: http://kinlane-productions.s3.amazonaws.com/up-image.php/sponsor/Walgreens_Type-Logo_Red_4c.jpg
  - name: Klout
    link: https://klout.com/s/developers/home
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/klout-logo-color-dark.png
  - name: SmartBear
    link: http://smartbear.com/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/Color-SmartBear_Logo.png
  - name: Akana
    link: https://www.akana.com/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/akana-logo.png
  - name: Cloud Elements
    link: http://cloud-elements.com/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/cloud-elements-logo.png
  - name: JustAPIs by AnyPresence
    link: http://www.anypresence.com/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/jusapis-logo.png
  - name: Apiary
    link: https://apiary.io/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/apiary-logo.png
  - name: Swagger
    link: http://swagger.io/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/swagger-logo.png
  - name: Iron.io
    link: http://iron.io/
    logo: https://s3.amazonaws.com/kinlane-productions/events/apistrat-austin/sponsors/ironio-logo.png

organizers:
  - name: 3Scale
    link: http://www.3scale.net/
    logo: http://apidaysberlin2015.apistrat.com/wp-content/uploads/2014/11/3scale-logo-new.png
  - name: API Evangelist
    link: http://apievangelist.com/
    logo: http://apidaysberlin2015.apistrat.com/wp-content/uploads/2014/11/api-evangelist-logo1.png
